### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Payalpatil1999** [nishchalraj/Auditorium#2]
Sir can you say me what is the username and password or where you have set the username and password . Please !

**Comment by thenishchalraj** [comment]
Look into #1 and carefully read the discussion.

**Comment by Payalpatil1999** [comment]
Sir please help me i cant understand please sir please Just help me once for this username and password thats it please sir

**Comment by thenishchalraj** [comment]
Can't explain like this. What's your mail? We will contact there.

**Comment by Payalpatil1999** [comment]
1999payalpatil@gmail.com This is my mail please sir help me

**Comment by Payalpatil1999** [comment]
Just want the admin username & password . Once it is done I will be so thankful to you sir please help me out

**Comment by Payalpatil1999** [comment]
sir please help me please I beg you sir please help me 😭😭 @nishchalraj 
Only you can help me sir please 🙏
